$(document).ready(()=>{
  $("#texto").show(600);
  $("#pdf").hide(600);
  $("#video").hide(600);
  $("#pregunta").hide(600);
});
$("#btnTexto").click(()=>{
  $("#texto").hide(600);
  $("#pdf").show(600);
  $("#video").hide(600);
  $("#pregunta").hide(600);
});
$("#btnPdf").click(()=>{
  $("#texto").hide(600);
  $("#pdf").hide(600);
  $("#video").show(600);
  $("#pregunta").hide(600);
});
$("#btnVideo").click(()=>{
  $("#texto").hide(600);
  $("#pdf").hide(600);
  $("#video").hide(600);
  $("#pregunta").show(600);
});